variables:
  GRADLE_USER_HOME: "/opt/runner-cache/$CI_JOB_NAME/gradle"

java_build_test_deploy:
  image: krjura/java-17-build-env:1.0.0
  stage: build
  tags:
    - docker
  only:
    - master
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-java"
    expire_in: "1 day"
    when: on_success
    paths:
      - "build/install"
  script:
    - bash ./gradlew --no-daemon --info -Dspring.profiles.active=test,jenkins build installDist

angular_build_test_deploy:
  image: krjura/angular-build-env:16.3-b1
  stage: build
  tags:
    - docker
  only:
    - master
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-angular"
    expire_in: "1 day"
    when: on_success
    paths:
      - "frontend/angular-web/dist"
  cache:
    key: $CI_JOB_NAME
    when: 'on_success'
    paths:
      - frontend/angular-web/node_modules
  script:
    - bash ./frontend/angular-web/build-frontend.sh
