management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  servlet:
    context-path: /
    session:
      timeout: 3600
  port: 25000
  compression:
    enabled: true
  use-forward-headers: true

spring:
  main:
    allow-bean-definition-overriding: true
  pid:
    file: dev-tools.pid
  application:
    name: dev-tools
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: "https://demo.org/auth/realms/demo/protocol/openid-connect/auth"
            token-uri: "https://demo.org/auth/realms/demo/protocol/openid-connect/token"
            user-info-uri: "https://demo.org/auth/realms/demo/protocol/openid-connect/userinfo"
            jwk-set-uri: "https://demo.org/auth/realms/demo/protocol/openid-connect/certs"
            user-name-attribute: "name"
        registration:
          keycloak:
            client-id: "demo.org"
            client-secret: "demo.org"
            client-name: "Dev Tools"
            redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: "authorization_code"
            scope:
              - "openid"
              - "email"
              - "profile"