management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

server:
  servlet:
    context-path: /
    session:
      timeout: 3600
  port: 25000
  compression:
    enabled: true
  forward-headers-strategy: framework

spring:
  main:
    allow-bean-definition-overriding: true
  pid:
    file: /tmp/dev-tools.pid
  application:
    name: dev-tools