---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "dev-tools"
  namespace: "dev-tools"
  labels:
    app: "dev-tools"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "dev-tools"
  template:
    metadata:
      labels:
        app: "dev-tools"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1200
        runAsGroup: 1200
        fsGroup: 1200
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - "dev-tools"
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: "dev-tools"
          image: "rg.fr-par.scw.cloud/krjura/dev-tools/dev-tools:10"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "500Mi"
              cpu: "100m"
      imagePullSecrets:
        - name: regcred