name: Gradle Build
on: [push]
jobs:
  gradle-build:
    runs-on: "ubuntu-latest"
    container:
      image: "eclipse-temurin:17.0.2_8-jdk-focal"
      volumes:
        - ${{ github.workspace }}:/opt/build
      env:
        GRADLE_USER_HOME: /opt/build/.gradle
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Cache"
        uses: "actions/cache@v2"
        with:
          path: |
            /opt/build/.gradle
          key: dev-tools-${{ runner.os }}-${{ hashFiles('/opt/build/build.gradle') }}
          restore-keys: |
            dev-tools-${{ runner.os }}-
      - run: pwd
      - run: env

      - name: "Build project"
        run: ./gradlew --no-daemon --info --build-cache -Dspring.profiles.active=test build jacocoTestReport

      - run: pwd
      - run: env
      - run: find /opt/build -type f