name: Gradle Build
on: [push]
jobs:
  gradle-build:
    runs-on: "ubuntu-latest"
    container:
      image: "krjura/java-17-build-env:1.0.0"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Cache"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.gradle
          key: "dev-tools"
      - run: pwd
      - run: env

      - name: "Build project"
        run: ./gradlew --no-daemon --info --build-cache -Dspring.profiles.active=test build jacocoTestReport
        
      - run: pwd
      - run: env